name: Semantic Release

### PREREQUISITE
  # .releaserc file
  # package.json 

on:
  workflow_call:

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Get GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          
      - uses: actions/checkout@master
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Semantic Release
        id: release
        uses: go-semantic-release/action@v1.23.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          changelog-generator-opt: "emojis=true"
