name: Semantic Release

### PREREQUISITE
  # .releaserc file
  # package.json 

on:
  workflow_call:
    secrets: 
      github-token:
        required: true
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.github-token }}

      - name: Semantic Release
        id: release
        uses: go-semantic-release/action@v1.23.0
        with:
          github-token: ${{ secrets.github-token }}
          changelog-generator-opt: "emojis=true"
